// File generated by FlutterFire CLI — do not edit manually.
// Run `flutterfire configure` to regenerate.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web is not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMrQNXC4mVWIecfQamJkIhFX8AEyPUAU',
    appId: '1:474371875450:android:8641d90b648f0033ef51c3',
    messagingSenderId: '474371875450',
    projectId: 'entwined-memories-app',
    storageBucket: 'entwined-memories-app.firebasestorage.app',
  );
}
